### ISSUE TITLE
[Feature Request] Use in Gpose

### ISSUE THREAD

**Issue by Lanselotto** [Eternita-S/Weatherman#10]
The interface is hidden in gpose making it unusable in gpose

**Comment by Eternita-S** [comment]
You'll need to go into `/xlsettings` and uncheck this option:
![image](https://user-images.githubusercontent.com/5073202/160281741-12b9c251-5919-4225-aec7-0973b8c4608b.png)

**Comment by Lanselotto** [comment]
I don't want all plugins to be visible in gpose, I just want the ones I need. I know it can be done because Penumbra works in Gpose even if the other windows are hidden.

**Comment by Eternita-S** [comment]
I'll add the option in next update

**Comment by Lanselotto** [comment]
thank you
