### ISSUE TITLE
Weatherman says my clock is wrong

### ISSUE THREAD

**Issue by thisischrys** [Eternita-S/Weatherman#11]
It isn't, we just (sunday night) entered Daylight Savings Time in EU.

**Comment by Eternita-S** [comment]
could you please post screenshots of:
1) https://time.is/
2) /weatherman - debug tab?

**Comment by thisischrys** [comment]
It no longer did it today when I logged in so can't reproduce it anymore.

**Comment by thisischrys** [comment]
![image](https://user-images.githubusercontent.com/2012611/161164299-cee37b43-e95c-4378-8e8f-bf803511868b.png)
![image](https://user-images.githubusercontent.com/2012611/161164380-dd871903-b931-4ad6-ab99-aec6dc7cab61.png)

**Comment by Eternita-S** [comment]
Well, your clock is indeed out of sync. I suggest synchronizing it.
Anyway in next update I will increase treshold and plugin will only notify about it if clock is off my more than 30 seconds
