### ISSUE TITLE
6.1 Support

### ISSUE THREAD

**Issue by Zebouski** [Eternita-S/Weatherman#13]
Currently, weatherman shows as an outdated plugin and cannot be installed or activated.

**Comment by Eternita-S** [comment]
Hello!
Weatherman now moved to official xivlauncher's repo. As a right now it is in testing section. Please enable plugin testing in `/xlsettings` - experimental and try installing again.

**Comment by Zebouski** [comment]
Got it installed and played around with the settings, couldnt find any issues or crashes, big thanks on all the work!
