### ISSUE TITLE
Weatherman not showing in the available plugin list

### ISSUE THREAD

**Issue by Rynn21** [Eternita-S/Weatherman#14]
Hey, weatherman isn't showing up in the available plugin list for me, even after adding the .json to the custom plugin repositories. Only weatherman extras shows up and it doesn't work at all (drop down doesn't work and it doesn't look the same). Suggestion? I had no issues with any of the other plugins.

**Comment by Eternita-S** [comment]
Hello, weatherman has been added into Dalamud's main repo and is currently in testing plugins. Please enable "plugin testing" option in `/xlsettings` - experimental and try again.

**Comment by Rynn21** [comment]
That did the trick. Thank you!
