### ISSUE TITLE
Request: Weather controls in dungeons and raids

### ISSUE THREAD

**Issue by Annullare** [Eternita-S/Weatherman#16]
Sorry to bother you, I wanna visit The Dead Ends at weather 'Inevitable', but it's not supported. I wonder: is it possible to support?

**Comment by Eternita-S** [comment]
Hello. You can install WeathermanExtras from my custom repo which can enable changing weather in dungeons: https://github.com/Eternita-S/MyDalamudPlugins#installation
However, in that particular dungeon, you will not receive desired effect as ground colors aren't tied to weather.
