### ISSUE TITLE
Time control doesn't work in GPose

### ISSUE THREAD

**Issue by MissingNoIOI** [Eternita-S/Weatherman#19]
While weathercontrol works fine, time control seems to be overriden when opening gpose. It works fine again once I leave it

**Comment by Eternita-S** [comment]
You will need to uncheck stop time/weather button in gpose for it to work there 

![image](https://user-images.githubusercontent.com/5073202/182047492-d801023c-e487-4c11-9777-a14adfcbf4df.png)
