### ISSUE TITLE
"Enable music control" not working properly?

### ISSUE THREAD

**Issue by Maxunit** [Eternita-S/Weatherman#3]
Hello Eternita-S,

I started using Weatherman 2.0 today and have "Real world time" active as a Global time control and also have "Enable music control" active (Orchestrion Plugin is installed) and I noticed, that it is either not working at all or at least not most of the time.

Example:

Right now, as of me writing this, it is 2:22 AM at my place, it is night time in Limsa, yet "I Am the Sea" is playing, the Daytime Theme.

I did check my Dalamud.log and...nothing.

Cheers,

Maxunit

**Comment by Eternita-S** [comment]
Well, music control just lets you override zone music, that's it.
Syncing bgm to time set through plugin is actully planned, but I will only be able to implement it after 6.0 since I don't really have much time now.

**Comment by Maxunit** [comment]
Ah okay, thanks. Then I misunderstood the feature. Then this "issue" can be closed.

Thanks for clarifying and for the quick response!
