### ISSUE TITLE
Clarification on "Unsafe options"

### ISSUE THREAD

**Issue by larrybox** [Eternita-S/Weatherman#5]
Due to the plugin no longer editing values that could affect things involving server responses, I am curious as to how unsafe the unsafe options are. Does activating the unsafe option edit these variables after all or send invalid messages to the server? Is there injection involved? If the unsafe options are used, it is detectable on the server and could you get banned?

Thank you for answering my query.

**Comment by Eternita-S** [comment]
There is only one unsafe option that gets unlocked with that checkbox and it allows you to forcefully set a weather that is not supported in the zone. Can lead to graphical glitch or crash, therefore it's called unsafe, that's it. Nothing of that is sent to server

**Comment by larrybox** [comment]
Thank you for answering my query so fast. I am relived to hear that the worst possible responce would be a crash - as I was thinking much worse things could happen.

When you say remove - are you going to completely remove the ability to force weather unsupported weather onto the maps? I think I may like seeing a sandstorm in the middle of the snowy mountains.

**Comment by Eternita-S** [comment]
Unfortunately, if a zone does not supports certain weather, all you will see is a black sky, so there is no point

**Comment by larrybox** [comment]
I see now. I made this thread after trying it just once - I see it's pointless. Thank you for answering my question.

**Comment by oorzkws** [comment]
@Eternita-S Was this functionality removed?
