### ISSUE TITLE
Unsafe option gone?

### ISSUE THREAD

**Issue by Rovan84127** [Eternita-S/Weatherman#9]
Hello,

Not sure if this was intentional or not, but has the option to use unsafe settings (i.e. wrong weather in zones, controlling time in certain instances) been taken away? I really appreciated the option to use unsafe settings, and would like to know if it's coming back or not.

**Comment by Eternita-S** [comment]
Using wrong weather leads to nothing but black sky and sometimes crashes, as for controlling time in certain instances - I'm working towards allowing it for any zone that supports it. But that will take some time. I've sent this plugin into main repo so I needed to make it a bit more safe to use

**Comment by Eternita-S** [comment]
Please use WeathermanExtras plugin from my custom repo to reenable missing options from now on, if you want to do so
